name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.6.3' 

      - name: Install Dependencies
        run: pnpm install

      - name: Install Prisma CLI
        run: pnpm add -g prisma

      - name: Set Environment Variables
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Ensure Prisma Packages Are in Sync
        run: |
          pnpm update @prisma/client prisma
          pnpm prisma generate

      - name: Build Project
        run: pnpm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd Todo-Backend
            git pull origin main
            pnpm install
            pnpm prisma generate
            pnpm run build
            pm2 restart backend || pm2 start dist/main.js --name backend
          envs: DATABASE_URL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
